### PR TITLE
Fix clang bugs

### LINKED ISSUE #1394: std::format usage breaks compilation with clang versions prior to 14 using C++20
Clang versions prior to 14 have missing support for std::format. Unfortunately they do have an effectively empty `<format>` header, so the test at lines 13 and 3006 of vulkan_to_string.hpp is satisfied, but causes a build error: No member named 'format' in namespace 'std'.

This affects the current release version of Xcode, which ships with clang 13.

Possibly a specific check for clang 14+ is required before use of std::format?

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes compilation using clang. 

- For clang-16 on Linux using libstdc++. Include <utility> for `std::exchange` 
```
In file included from /home/stephan/projects/Vulkan-Hpp/debug/RAII_Samples/SurfaceFormats/CMakeFiles/RAII_SurfaceFormats.dir/cmake_pch.hxx:5:
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:28:14: error: no template named 'exchange' in namespace 'std'; did you mean simply 'exchange'?
      return std::exchange<T>( obj, std::forward<U>( newValue ) );
             ^~~~~
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:25:49: note: 'exchange' declared here
    VULKAN_HPP_CONSTEXPR_14 VULKAN_HPP_INLINE T exchange( T & obj, U && newValue )
                                                ^
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:28:14: error: no template named 'exchange' in namespace 'std'; did you mean simply 'exchange'?
      return std::exchange<T>( obj, std::forward<U>( newValue ) );
             ^~~~~
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:25:49: note: 'exchange' declared here
    VULKAN_HPP_CONSTEXPR_14 VULKAN_HPP_INLINE T exchange( T & obj, U && newValue )

```
- For clang-13 on Mac using libc++. Use more reliable feature test macro for `std::format`. Fixes #1394

### CODE REVIEW

File: VulkanHppGenerator.cpp [hunk 1]
```diff
@@ -515,7 +516,7 @@ void VulkanHppGenerator::generateVulkanToStringHppFile() const
 
 #include <vulkan/vulkan_enums.hpp>
 
-#if ( ( 20 <= VULKAN_HPP_CPP_VERSION ) && __has_include( <format> ) )
+#if ( ( 20 <= VULKAN_HPP_CPP_VERSION ) && __cpp_lib_format )
```
Comment (theHamsta) [inline VulkanHppGenerator.cpp:519]: the check for cpp 20 is actually not necessary. `#if __cpp_lib_format` would be enough

**Comment by theHamsta** [comment]
`std::format` is usable with clang and g++. But it appears that they don't advertise full support via `__cpp_lib_format` in contrast to MSVC

File: VulkanHppGenerator.cpp [hunk 2]
```diff
@@ -405,6 +405,7 @@ void VulkanHppGenerator::generateVulkanRAIIHppFile() const
 #  define VULKAN_RAII_HPP
 
 #include <memory>
+#include <utility> // std::exchange
```
Comment (asuessenbach) [inline VulkanHppGenerator.cpp:408]: Please include `utility` only if `( 14 <= VULKAN_HPP_CPP_VERSION )`.

File: VulkanHppGenerator.cpp (hunk 1 above)
Comment (asuessenbach) [reply VulkanHppGenerator.cpp:519]: That's right. That is, please remove the check against `VULKAN_HPP_CPP_VERSION`.

**Review by asuessenbach — CHANGES_REQUESTED** [review]

File: VulkanHppGenerator.cpp (hunk 2 above)
Comment (theHamsta) [reply VulkanHppGenerator.cpp:408]: both `std::exchange` and `std::forward` (https://en.cppreference.com/w/cpp/utility/forward) require `<utility>`

**Review by asuessenbach — APPROVED** [review]
